apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-form-backend
  namespace: smart-form-prediction
  labels:
    app: smart-form-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: smart-form-backend
  template:
    metadata:
      labels:
        app: smart-form-backend
    spec:
      containers:
        - name: backend
          image: smart-form-backend:latest
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: smart-form-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: smart-form-config
                  key: BACKEND_PORT
            - name: DATA_PATH
              valueFrom:
                configMapKeyRef:
                  name: smart-form-config
                  key: DATA_PATH
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: smart-form-config
                  key: CORS_ORIGIN
          volumeMounts:
            - name: data-storage
              mountPath: /app/data
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: smart-form-data-pvc
