apiVersion: v1
kind: Service
metadata:
  name: smart-form-frontend-service
  namespace: smart-form-prediction
  labels:
    app: smart-form-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: smart-form-frontend

---
apiVersion: v1
kind: Service
metadata:
  name: smart-form-backend-service
  namespace: smart-form-prediction
  labels:
    app: smart-form-backend
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: smart-form-backend
